config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'shops/index' => 'shops#index'
   
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login' => 'users#login_form'
  post 'login' => 'users#login'
  post 'logout' => 'users#logout'

  post 'bookmarks/:shop_id/create' => 'bookmarks#create'
  delete 'bookmarks/:shop_id/destroy' => 'bookmarks#destroy'
  get 'bookmarks/index' => 'bookmarks#index'

  resources :users, only: [:show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, {presence: true, uniqueness: true}
	has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include Common
	
	before_action :authenticate_user, {only: [:show, :edit, :update, :logout]}
	before_action :restrict_current_user, {only: [:login, :login_form, :new, :create]}
	before_action :ensure_correct_user, {only: [:edit, :show, :update]}
	
	def new
		@user = User.new
	end
	
	def show
		@user = User.find_by(id: params[:id])
	end
	
	def create
		@user = User.new(user_params)

		if @user.save
			flash[:notice]  = "Signed up!"
			session[:user_id] = @user.id
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def edit
		@user = User.find_by(id: params[:id])
	end

	def update
		@user =  User.find_by(id: params[:id])
		if @user.update_attributes(user_params)
			flash[:notice] = "Account information updated"
			redirect_to user_path(@user)
		else
			render 'edit'
		end
		
	end

	def login_form
		#@user = User.new
	end

	def login
		@user = User.find_by(email: params[:email])

		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			flash[:notice] = "Login Succeeded"
			redirect_to root_path
		else
			@error_message = "email or password is wrong"
			@email = params[:email]
			@password = params[:password]
			render 'login_form'
		end
	end

	def logout
		session[:user_id] = nil
		flash[:notice] = "Logged out"
		redirect_to login_path
	end


private
	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">Edit Account</div>
    <div class="form users-form">
      <div class="form-body">
        <%= render 'shared/error_messages' %>
      	<%= form_for(@user, url: user_path, method: :put) do |f| %>
      		<%= f.label :Name %>
      		<%= f.text_field :name %>
      		<%= f.label :Email %>
      		<%= f.email_field :email %>
	        <%= f.submit :Save%>   
	    <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-login">
  <div class="container">
    <div class="form-heading">Login</div>
    <div class="form users-form">
      <% if @error_message %>
        <div class="form-error">
          <%= @error_message %>
        </div>
      <% end %>
      <div class="form-body">
      	<%= form_tag(url: "login", method: :post) do %>
      		<%= label_tag :Email %>
      		<%= text_field_tag(:email, value = @email) %>
          <%= label_tag :Password %>
          <%= password_field_tag(:password, value = @password) %>
	        <%= submit_tag :Login%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">Signup Form</div>
    <div class="form users-form">
      <div class="form-body">
        <%= render 'shared/error_messages' %>
      	<%= form_for(@user, url: signup_path) do |f| %>
      		<%= f.label :name, "Name" %>
      		<%= f.text_field :name %>
      		<%= f.label :email, "Email" %>
      		<%= f.email_field :email %>

          <%= f.label :passoword, "Password" %>
          <%= f.password_field :password %>

          <%= f.label :password_confirmation, "Password Confirmation" %>
          <%= f.password_field :password_confirmation %>


	        <%= f.submit :Signup%>
	    <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">Accont Information</div>
    <div class="form users-form">
      <div class="form-body">
      	<p>Name:
         	<%= @user.name %>
        </p>
      	<p>Email:
          <%= @user.email %>
        </p>
        <% if @current_user.id == @user.id %>
          <%= link_to("Edit", edit_user_path(@user), class: "btn-submit")%>
        <% end %>
      </div>
    </div>
  </div>
</div>