config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'shops/index' => 'shops#index'
   
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login' => 'users#login_form'
  post 'login' => 'users#login'
  post 'logout' => 'users#logout'

  post 'bookmarks/:shop_id/create' => 'bookmarks#create'
  delete 'bookmarks/:shop_id/destroy' => 'bookmarks#destroy'
  get 'bookmarks/index' => 'bookmarks#index'

  resources :users, only: [:show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
  <div class="header-logo">
    <a href="/">Restaurant</a>
  </div>
  <ul class="header-menus">

    <li>
      <a href="/">Home</a>
    </li>
    <% if @current_user %>
      <li>
        <%= link_to(@current_user.name,  user_path(@current_user))%>
      </li>
      <li>
        <%= link_to("Bookmarks",  bookmarks_index_path)%>
      </li>
      <li>
        <%= link_to("Log out", logout_path, method: :post)%>
      </li>
    <% else %>
      <li>
        <%= link_to("Sign Up", signup_path)%>
      </li>
      <li>
        <%= link_to("Log In", login_path)%>
      </li>
    <% end %>
  </ul>
</header>


<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    
</script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>